-- SELECT * FROM HR.EMPLOYEES
-- DESC HR.EMPLOYEES

-- ### DATE AND DATE RELATED FUNCTIONS
--  THIS FUNCTIONS ARE USED FOR DATE RELATED FUNCTIONS

-- SELECT EMPLOYEE_ID, HIRE_DATE,FIRST_NAME,LAST_NAME FROM HR.EMPLOYEES
-- SELECT EMPLOYEE_ID, HIRE_DATE,FIRST_NAME,LAST_NAME, SYSDATE FROM HR.EMPLOYEES
-- ## SYSDATE == IT GIVE TIME WHEN WE GETTING FETCH THAT DATA.....

-- ## ROWNUM OPERATOR... WHICH CAN HELP US FILTER ROW WHICH WE WANT.. 
-- SELECT EMPLOYEE_ID, HIRE_DATE,FIRST_NAME,LAST_NAME, SYSDATE FROM HR.EMPLOYEES WHERE ROWNUM <=3
-- HERE WE FILTER ONLY 3 ROW WHICH GIVE US HELP ROW WORK ON LARGE DATA..

-- ##ADD_MONTHS == FOR ADDING MONTHS
-- FOR ADD_MONTHS WE CAN + OR - MONTHS AS PER OUR REQUIREMENT
-- SELECT HIRE_DATE, ADD_MONTHS(HIRE_DATE,6) AS AFTER_6_MONTHS FROM HR.EMPLOYEES ---ADDING MONTHS

-- SELECT HIRE_DATE, ADD_MONTHS(HIRE_DATE, -4) AS BEFOR_4_MONTHS FROM HR.EMPLOYEES --- SUBSTRACTING MONTHS

-- ## MONTHS_BETWEEN FUNCTION == its used for findg data between specific months perriod
-- SELECT MONTHS_BETWEEN(SYSDATE,HIRE_DATE) AS EX_MONTHS FROM HR.EMPLOYEES -- THIS REPRESENTSS MONTHS

--  SELECT MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12 AS EX_YEARS FROM HR.EMPLOYEES -- ALSO WE CONVERT IT IN YEARS ALSO JUST DEVIDE BY 12

-- SELECT MONTHS_BETWEEN(SYSDATE,HIRE_DATE)*30 AS EX_DAYS FROM HR.EMPLOYEES -- HERE WE CONVERT IT IN DAYS BY MULTIPLYING BY 30

--  ##NEXT_DAY == this function is used for find next OCCURING DAY AND DATE
-- SELECT SYSDATE,NEXT_DAY(SYSDATE,'MONDAY') FROM DUAL

-- ## LAST_DAY== IT SHOWS LAST DAY MONTH (END DAY OF MONTH)
-- SELECT SYSDATE,LAST_DAY(SYSDATE) FROM DUAL

-- SELECT HIRE_DATE,LAST_DAY(HIRE_DATE) FROM HR.EMPLOYEES

-- ## ROUND FUCTION== IT ROUND DATE AROUND NEAREST MONTH OR YEAR
-- SELECT HIRE_DATE,ROUND(HIRE_DATE , 'MONTH') AS ROUND_MONTH FROM HR.EMPLOYEES

-- ### EXTRACT FUNCTION== ITS HELP TO EXTRACT YEARS,MONTHS,DAY 
-- SELECT EXTRACT(YEAR FROM HIRE_DATE) AS HIRE_YEAR FROM HR.EMPLOYEES --- HERE WE ARE EXTRACTING YEAR

-- SELECT EXTRACT(MONTH FROM HIRE_DATE) AS HIRE_YEAR FROM HR.EMPLOYEES --- HERE WE ARE EXTRACTING MONTH

-- SELECT EXTRACT(DAY FROM HIRE_DATE) AS HIRE_YEAR FROM HR.EMPLOYEES --- HERE WE ARE EXTRACTING DAY

-- ##LOCALTIMESTAMP== TO FIND OUT  LOCAL TIME
-- SELECT LOCALTIMESTAMP FROM DUAL
-- SELECT EXTRACT (HOUR FROM LOCALTIMESTAMP),
-- EXTRACT(MINUTE FROM LOCALTIMESTAMP),
-- EXTRACT(SECOND FROM LOCALTIMESTAMP) FROM DUAL

-- ## SPECIFIC KEYWORD **INTERVAL***
-- SELECT LOCALTIMESTAMP,LOCALTIMESTAMP+INTERVAL'10' DAY AS PLUS10DAY FROM DUAL -- FOR NEXT 10 DAYS
-- SELECT LOCALTIMESTAMP,LOCALTIMESTAMP-INTERVAL'15' DAY AS LAST15DAY FROM DUAL --- FOR PAST DAYS
--  SELECT LOCALTIMESTAMP,LOCALTIMESTAMP+INTERVAL'15' HOUR AS PLUS8HOURS FROM DUAL -- FOR UPCOMING HOURS
-- BY USING INTERVAL FUNCTION WE CAN ALSO MINUTES, SECOND

-- SELECT LOCALTIMESTAMP,LOCALTIMESTAMP+INTERVAL '2 6:15' day to minute as plus2days_6_hours_15minute from DUAL
-- here '2 6:15' in this 2=day,6=hour,15=minutes

-- SELECT LOCALTIMESTAMP,LOCALTIMESTAMP+INTERVAL '2 6:15:45'
--  day to second as plus2days_6_hours_15minute_45second from DUAL







































