-- SELECT * FROM HR.EMPLOYEES

-- ## OPERATINS
-- ## FUNCTIONS

-- DESC HR.EMPLOYEES

--#### CHARACTER FUNCTIONS
-- It is specifically used for character data
-- SELECT * FROM DUAL
--  UPPER FUCTION
-- SELECT FIRST_NAME,UPPER (FIRST_NAME) FROM HR.EMPLOYEES

-- LOWER  FUNCTION
-- SELECT FIRST_NAME,LOWER (FIRST_NAME) FROM HR.EMPLOYEES

-- INITCAP-- THIS FUCTION CAPITALIZE FIRST LETTER OF EVERY WORD
-- SELECT FIRST_NAME,INITCAP(FIRST_NAME) FROM HR.EMPLOYEES

-- LENGTH FUCTION
--  SELECT FIRST_NAME,LENGTH(FIRST_NAME) FROM HR.EMPLOYEES

-- SELECT UPPER ('shubham') as UPPER FROM DUAL

-- SELECT LOWER ('SHUBHAM') AS LOWER FROM DUAL
 
--  SELECT INITCAP ('i am going to hometown') from dual

--  SELECT INITCAP ('i am going to hometown')as TITLE, LENGTH('DEVIBHOYARE') AS LENGTH from dual

-- ## SUBTRING FUNCTION (SUBSTR)
-- SUBSTR(DATA,2,4) HERE 2 IS START PONIT AND 4 IS HOW CHARACTER AFTER 2 WE HAVE TO FETCH
-- SELECT SUBSTR('SHUBHAM SARADE',4,5)AS SUBSTRING FROM DUAL
-- IN SUBSTRING FIRST PARAMETER IS STRING, SECOND IS STARTING POINT AND THIRD IS HOW MUCH LENGTH WE WANT

-- ##INSTRING FUNCTION (INSTR)
-- SELECT INSTR('DATASCIENCE','SCINCE')FROM DUAL
-- In INSTR WE CAN FIND POSITION OF SPECIFIC STRING

-- ## LEFT PAD (LPAD)
-- SELECT LPAD('DAATA',8,'#') FROM DUAL
-- SELECT LPAD('DATA',1,'#')

-- ##RIGHT PADDING (RPAD)
-- SELECT RPAD('DATA',10,'@')

-- ##TRIM FUNCTION== THIS FUCTION REMOVES SPACES FROM BOTH SIDES IF SPACE IS THERE
-- SELECT TRIM('  INDIA   ') FROM DUAL

-- ##REPLACE FUCTION
-- SELECT REPLACE('DATA SCIENCE','SCIENCE','ENGINEERING') FROM DUAL

-- ## CONCAT FUNCTIO== WE CAN JOIN TOW STRINGS
-- SELECT CONCAT('DATA','SCIENCE') AS C  FROM DUAL
-- SELECT CONCAT('DATA',' ','SCIENCE') AS C FROM DUAL

-- ## LEFT TRIM & RIGHT TRIM FUNCTION
-- SELECT LTRIM('  DATA'), RTRIM('SCIENCE   ') FROM DUAL

-- ##ASCII ==  NUMERICAL CODE FOR A ALPHABET
-- SELECT ASCII('F') FROM DUAL

-- ##CHR == CONVERT NUMBER INTO ALPHABET
-- SELECT CHR(97) FROM DUAL

-- ##REVERSE FUNCTION
-- SELECT REVERSE('SHUBHAM') FROM DUAL
-- DESC HR.EMPLOYEES

-- TO FIND LENGTH OF EMAIL IN EMPLOYEES TABLE
-- SELECT EMAIL,LENGTH (EMAIL) FROM HR.EMPLOYEES

-- SELECT EMAIL, SUBSTR(EMAIL,1,4) FROM HR.EMPLOYEES

-- SELECT EMAIL, SUBSTR(EMAIL,LENGTH(EMAIL)-2,3) FROM HR.EMPLOYEES

-- SELECT PHONE_NUMBER FROM HR.EMPLOYEES
-- SELECT PHONE_NUMBER,RTRIM(PHONE_NUMBER,'0') FROM HR.EMPLOYEES

-- SELECT FIRST_NAME,LAST_NAME FROM HR.EMPLOYEES
-- SELECT CONCAT(SUBSTR(FIRST_NAME,1,3),SUBSTR(LAST_NAME,1,3)) AS C FROM HR.EMPLOYEES
-- SELECT SUBSTR(FIRST_NAME,1,3) ||SUBSTR (LAST_NAME,1,3) FROM HR.EMPLOYEES

-- SELECT PHONE_NUMBER FROM HR.EMPLOYEES
-- SELECT PHONE_NUMBER ,RPAD('X',LENGTH(PHONE_NUMBER)-4,'X')||SUBSTR(PHONE_NUMBER,-4)
-- AS MASKED_NUMBER FROM HR.EMPLOYEES

-- ### NUMBER BASED FUCTIONS
-- ##CEIL AND FLOOR FUNCTION
-- SELECT CEIL(15.2),FLOOR(12.8) FROM DUAL


-- ## ABSOLUTE VALUE -- IF THERE IS NEGATIVE VALUE IT CONVERT IN TO POSITIVE VALUE
-- SELECT ABS(-134) FROM DUAL

-- ##POWER  FUNCTION 
-- SELECT POWER (2,5) FROM DUAL

-- ## MODULUS OPERATOR == IT GIVES US THE REMIDER
-- SELECT MOD(43,8) FROM DUAL

-- ##SQAREROOT FUNCTION 
-- SELECT SQRT(36) FROM DUAL

-- ##SIGN FUNCTION == IT GIVE IF THRE ANY NEGATIVE NUBER ITS SHOWS -1 ,IF THERE IS A 0 IT SHOWS 0 & IF THERE IS AN POSITIVE NUMBER IT SHOWS +1
-- SELECT SIGN(-12),SIGN(25),SIGN(0) FROM DUAL

-- ##LOG FUNCTIONS
-- SELECT LN(100) FROM DUAL
-- SELECT LOG(2,10) FROM DUAL

-- ##GREATEST  == IT REFERS TO LARG NUMBER
-- SELECT GREATEST(10,80,12,43,98) FROM DUAL

-- ##TRIGNOMETRIC FUNCTIONS
-- SELECT SIN(1), COS(0), TAN(1) FROM DUAL
-- SELECT ASIN (1),ACOS(1),ATAN(1) FROM DUAL

--  ##HYPERBOLIC FUCTION
-- SELECT SINH(1),COSH(1),TANH(1) FROM DUAL

-- ##ROUND FUNCTION  == ITS ABOUT ROUNDING THE VALUES
-- SELECT ROUND(1224.2345678,3) FROM DUAL
























